name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: |
          MAX_TRIES=2
            run_with_retry() {
             n=1
             until [ $n -gt $MAX_TRIES ]
             do
                echo "Starting build attempt $n"
                ./gradlew assembleDebugAndroidTest && break
                n=$[$n+1]
                sleep 2
             done
             if [ $n -gt $MAX_TRIES ]; then
               echo "Max tries reached ($MAX_TRIES)"
               exit 1
             fi
            }
            run_with_retry
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Coverage
        run: ./gradlew testCoverage


      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.1
        with:
          path: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          debug-mode: false


