name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: |
          MAX_TRIES=2
            run_with_retry() {
             n=1
             until [ $n -gt $MAX_TRIES ]
             do
                echo "Starting build attempt $n"
                ./gradlew assembleDebugAndroidTest && break
                n=$[$n+1]
                sleep 2
             done
             if [ $n -gt $MAX_TRIES ]; then
               echo "Max tries reached ($MAX_TRIES)"
               exit 1
             fi
            }
            run_with_retry
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Unit Test with Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.14.3
        with:
          api-level: 33
          script: ./gradlew connectedCheck


      - name: generate report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/debug

