name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: |
          MAX_TRIES=2
            run_with_retry() {
             n=1
             until [ $n -gt $MAX_TRIES ]
             do
                echo "Starting build attempt $n"
                ./gradlew assembleDebugAndroidTest && break
                n=$[$n+1]
                sleep 2
             done
             if [ $n -gt $MAX_TRIES ]; then
               echo "Max tries reached ($MAX_TRIES)"
               exit 1
             fi
            }
            run_with_retry

      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew testDebugUnitTest

      - name: Generate JaCoCo Badge
          id: jacoco
          uses: cicirello/jacoco-badge-generator@v2
          with:
            jacoco-csv-file: build/reports/jacoco/jacoco.csv
