name: Android Pull Request & Master CI
on:
  push:
    branches:
      - 'master'

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      - name: setting up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Build the app
        run: |
          MAX_TRIES=2
            run_with_retry() {
             n=1
             until [ $n -gt $MAX_TRIES ]
             do
                echo "Starting build attempt $n"
                ./gradlew bundleRelease && break
                n=$[$n+1]
                sleep 2
             done
             if [ $n -gt $MAX_TRIES ]; then
               echo "Max tries reached ($MAX_TRIES)"
               exit 1
             fi
            }
            run_with_retry

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGN_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.STORE_KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT}}
          packageName: com.example.githubaction
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: Pipeline deployment app track










