name: Build
on: push

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ github.ref }} # The branch where you commit
          base: master # Don't forget to specify the right base branch here

      - name: Run Coverage
        run: ./gradlew jacocoTestReport

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: app/build/reports/jacoco/jacocoTestReport/html/








